# @import ./varInit.http

@productId=6954187d478854392e9c9bf6
@quantity=2

###

GET {{host}}/cart
Authorization: Bearer {{token}}

###
POST {{host}}/cart
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "productId": "{{productId}}",
    "quantity": {{quantity}}
}   

###
PATCH {{host}}/cart
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "productId": "{{productId}}",
    "quantity": {{quantity}}
}

###
DELETE {{host}}/cart/{{productId}}
Authorization: Bearer {{token}}