@host = http://localhost:8000/api/v1

@name = gia bao
@email = giabao@gmail.com
@password = 123456
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NTQxMjQ0MDAwZTdjNDY4OGYxODFiNiIsIm5hbWUiOiJnaWEgYmFvIiwiZW1haWwiOiJnaWFiYW9AZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzY3MTE5Mjg3LCJleHAiOjE3Njk3MTEyODd9.APD2Tk1vsYcv_mHJcJwkJqnu5yJudcHMpliKlnGucI8
